### ISSUE TITLE
 Practica de Operaciones Básicas 

### ISSUE THREAD

**Issue by Berenice1719** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Berenice1719#4]
[Practica 3Ejercicios de OperacionesGuadalupe Berenice..pdf](https://github.com/user-attachments/files/16859770/Practica.3Ejercicios.de.OperacionesGuadalupe.Berenice.pdf)

**Comment by YulianaMorales18** [comment]
portada 25/25
procedimiento 25/25
figuras ilustrativas y fotografías 25/25
resultados y conclusiones 25/25

final 100/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
